import { initializeApp } from "firebase/app";
import { getDatabase, ref, set } from "firebase/database";
import "@firebase/auth";
import { getReactNativePersistence, initializeAuth } from "firebase/auth";
import ReactNativeAsyncStorage from "@react-native-async-storage/async-storage";

const firebaseConfig = {
  apiKey: process.env.apiKey,
  authDomain: process.env.authDomain,
  projectId: process.env.projectId,
  storageBucket: process.env.storageBucket,
  messagingSenderId: process.env.messagingSenderId,
  appId: process.env.appId,
  measurementId: process.env.measurementId,
};

const app = initializeApp(firebaseConfig);
const db = getDatabase(app);
const auth = initializeAuth(app, {
  persistence: getReactNativePersistence(ReactNativeAsyncStorage),
});

const locations = [
  {
    id: 0,
    name: "Stevens Insitute of Technology",
    latitude: 40.7448,
    longitude: -74.0256,
    latitudeDelta: 0.04,
    longitudeDelta: 0.02,
    description: "cheap college",
    visited: false,
  },
  {
    id: 1,
    name: "Benny Tudinos",
    latitude: 40.74424,
    longitude: -74.02912,
    latitudeDelta: 0.04,
    longitudeDelta: 0.02,
    description: "pizza meme",
    visited: false,
  },
  {
    id: 2,
    name: "Hoboken Terminal",
    latitude: 40.7349,
    longitude: -74.0291,
    latitudeDelta: 0.04,
    longitudeDelta: 0.02,
    description: "fun times...",
    visited: false,
  },
  {
    id: 3,
    name: "Pier A Park",
    latitude: 40.736,
    longitude: -74.027,
    latitudeDelta: 0.04,
    longitudeDelta: 0.02,
    description: "scenic waterfront park",
    visited: false,
  },
  {
    id: 4,
    name: "Hoboken Historical Museum",
    latitude: 40.752,
    longitude: -74.0275,
    latitudeDelta: 0.04,
    longitudeDelta: 0.02,
    description: "local history showcase",
    visited: false,
  },
  {
    id: 5,
    name: "Castle Point Lookout",
    latitude: 40.745,
    longitude: -74.023,
    latitudeDelta: 0.04,
    longitudeDelta: 0.02,
    description: "stunning city views",
    visited: false,
  },
  {
    id: 6,
    name: "Carlos Bakery",
    latitude: 40.7378,
    longitude: -74.0307,
    latitudeDelta: 0.04,
    longitudeDelta: 0.02,
    description: "famous bake shop",
    visited: false,
  },
  {
    id: 7,
    name: "Elysian Park",
    latitude: 40.7509,
    longitude: -74.0249,
    latitudeDelta: 0.04,
    longitudeDelta: 0.02,
    description: "peaceful green space",
    visited: false,
  },
  {
    id: 8,
    name: "Hoboken Cove Community Boathouse",
    latitude: 40.7425,
    longitude: -74.0284,
    latitudeDelta: 0.04,
    longitudeDelta: 0.02,
    description: "boating and kayaking",
    visited: false,
  },
  {
    id: 9,
    name: "Church Square Park",
    latitude: 40.7417,
    longitude: -74.0312,
    latitudeDelta: 0.04,
    longitudeDelta: 0.02,
    description: "historic urban park",
    visited: false,
  },
  {
    id: 10,
    name: "Hoboken Fire Department Museum",
    latitude: 40.7465,
    longitude: -74.0322,
    latitudeDelta: 0.04,
    longitudeDelta: 0.02,
    description: "firefighting history museum",
    visited: false,
  },
  {
    id: 11,
    name: "Sinatra Park",
    latitude: 40.7381,
    longitude: -74.0278,
    latitudeDelta: 0.04,
    longitudeDelta: 0.02,
    description: "waterfront park with Sinatra tribute",
    visited: false,
  },
  {
    id: 12,
    name: "Hoboken Public Library",
    latitude: 40.7456,
    longitude: -74.0321,
    latitudeDelta: 0.04,
    longitudeDelta: 0.02,
    description: "historic library with community events",
    visited: false,
  },
  {
    id: 13,
    name: "Mile Square Theatre",
    latitude: 40.7423,
    longitude: -74.0346,
    latitudeDelta: 0.04,
    longitudeDelta: 0.02,
    description: "performing arts venue",
    visited: false,
  },
  {
    id: 14,
    name: "Hoboken Cove",
    latitude: 40.7489,
    longitude: -74.0241,
    latitudeDelta: 0.04,
    longitudeDelta: 0.02,
    description: "urban beach and recreation area",
    visited: false,
  },
  {
    id: 15,
    name: "Maxwell Place Park",
    latitude: 40.7427,
    longitude: -74.0247,
    latitudeDelta: 0.04,
    longitudeDelta: 0.02,
    description: "riverside park with playground",
    visited: false,
  },
  {
    id: 16,
    name: "Hoboken Historical Museum's Fire Department Museum",
    latitude: 40.748,
    longitude: -74.03,
    latitudeDelta: 0.04,
    longitudeDelta: 0.02,
    description: "vintage fire apparatus and memorabilia",
    visited: false,
  },
  {
    id: 17,
    name: "Stevens Park",
    latitude: 40.7453,
    longitude: -74.0289,
    latitudeDelta: 0.04,
    longitudeDelta: 0.02,
    description: "park with sports fields and dog run",
    visited: false,
  },
  {
    id: 18,
    name: "Madison Bar & Grill",
    latitude: 40.7502,
    longitude: -74.0271,
    latitudeDelta: 0.04,
    longitudeDelta: 0.02,
    description: "popular local eatery",
    visited: false,
  },
  {
    id: 19,
    name: "Hudson River Waterfront Walkway",
    latitude: 40.734,
    longitude: -74.0268,
    latitudeDelta: 0.04,
    longitudeDelta: 0.02,
    description: "scenic walking path along the river",
    visited: false,
  },
  {
    id: 20,
    name: "Washington Street",
    latitude: 40.741,
    longitude: -74.0295,
    latitudeDelta: 0.04,
    longitudeDelta: 0.02,
    description: "vibrant shopping and dining district",
    visited: false,
  },
  {
    id: 21,
    name: "Frank Sinatra Drive",
    latitude: 40.7395,
    longitude: -74.0267,
    latitudeDelta: 0.04,
    longitudeDelta: 0.02,
    description: "scenic drive along the waterfront",
    visited: false,
  },
  {
    id: 22,
    name: "Hoboken Farmers Market",
    latitude: 40.7424,
    longitude: -74.033,
    latitudeDelta: 0.04,
    longitudeDelta: 0.02,
    description: "local produce and artisanal foods",
    visited: false,
  },
  {
    id: 23,
    name: "Columbus Park",
    latitude: 40.7492,
    longitude: -74.0313,
    latitudeDelta: 0.04,
    longitudeDelta: 0.02,
    description: "community park with playgrounds",
    visited: false,
  },
  {
    id: 24,
    name: "Hoboken Skatepark",
    latitude: 40.7432,
    longitude: -74.0319,
    latitudeDelta: 0.04,
    longitudeDelta: 0.02,
    description: "skateboarding and BMX facility",
    visited: false,
  },
  {
    id: 25,
    name: "Hoboken City Hall",
    latitude: 40.7377,
    longitude: -74.0325,
    latitudeDelta: 0.04,
    longitudeDelta: 0.02,
    description: "historic municipal building",
    visited: false,
  },
  {
    id: 26,
    name: "Symposia Bookstore",
    latitude: 40.7468,
    longitude: -74.0281,
    latitudeDelta: 0.04,
    longitudeDelta: 0.02,
    description: "independent bookstore and community space",
    visited: false,
  },
  {
    id: 27,
    name: "Hoboken Waterfront Walkway",
    latitude: 40.7365,
    longitude: -74.0272,
    latitudeDelta: 0.04,
    longitudeDelta: 0.02,
    description: "picturesque path along the Hudson River",
    visited: false,
  },
  {
    id: 28,
    name: "Stevens Institute of Technology Campus",
    latitude: 40.7439,
    longitude: -74.0246,
    latitudeDelta: 0.04,
    longitudeDelta: 0.02,
    description: "prestigious university with panoramic views",
    visited: false,
  },
  {
    id: 29,
    name: "Hoboken 9/11 Memorial",
    latitude: 40.7411,
    longitude: -74.0258,
    latitudeDelta: 0.04,
    longitudeDelta: 0.02,
    description: "memorial site honoring 9/11 victims",
    visited: false,
  },
];

const badges = [
  {
    id: 0,
    name: "Noobie",
    description: "Awarded for your first location visited!",
  },
  {
    id: 1,
    name: "Explorer",
    description: "Awarded for visiting three locations!",
  },
  {
    id: 2,
    name: "Adventurer",
    description: "Awarded for visiting 10 locations!",
  },
  {
    id: 3,
    name: "Foodie Adventurer",
    description: "Awarded for visiting 5 food locations!",
  },
  {
    id: 4,
    name: "Time Traveler",
    description: "Awarded for visiting 5 hisorical sites!",
  },
];

function writeLocationData(locations) {
  for (const location of locations) {
    const reference = ref(db, `locations/${location.id}`);
    set(reference, location);
  }
}

function writeBadgeData(badges) {
  for (const badge of badges) {
    const reference = ref(db, `badges/${badge.id}`);
    set(reference, badge);
  }
}

writeLocationData(locations);
writeBadgeData(badges);

export { app, db, auth };
