version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:21.2.0  # You can choose the Node.js version you need

    working_directory: ~/SSW555-Team12  # Update the working directory to match the repository name

    steps:
      - checkout:
          path: ~/SSW555-Team12  # Update the path to match the repository name

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Run tests
          command: npx jest --testPathPattern="^(?!.*TestVisitedLocationsScreen.*|.*TestBadgeCollectionScreen.*|.*TestMapScreen.*).*$"

workflows:
  version: 2
  build-and-test:
    jobs:
      - build

