name: Node.js CI

on:
  pull_request:
    branches: [ main ]

jobs:
  expo-start:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Install Dependencies
      run: npm install
    - name: Install CocoaPods
      run: sudo gem install cocoapods
    - name: Install Pods
      run: |
        if [ -d "ios" ]; then
          cd ios
          pod install
        fi
    - name: Start Expo
      run: npx eas-cli build --platform all --non-interactive
      env:
        CI: true