# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  pull_request:
    branches: [ main ]

jobs:
  expo-start:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Install Dependencies
      run: npm install
    - name: Install CocoaPods
      run: sudo gem install cocoapods
    - name: Install Pods
      run: |
        if [ -d "ios" ]; then
          cd ios
          pod install
        fi
    - name: Start Expo
      run: CI=1 npx expo start --non-interactive
      env:
        CI: true
